### ISSUE TITLE
Gradle build error on windows

### ISSUE THREAD

**Issue by DarrenRatcliffe** [spring-io/sagan#336]
I am getting a build error when performing the Gradle build command:

C:\Users\a538209\sagan\sagan-site>c:\users\a538209\sagan\gradlew build -x check
:sagan-client:compileJava UP-TO-DATE
:sagan-client:processResources UP-TO-DATE
:sagan-client:classes UP-TO-DATE
:sagan-client:npmInstall FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':sagan-client:npmInstall'.
  > A problem occurred starting process 'command 'npm''

I have npm installed and it can be called fine from the cmd prompt?

**Comment by Andromed** [comment]
Hello, I have the same problem. 

```consol
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sagan-client:npmInstall'.
> Process 'command 'npm'' finished with non-zero exit value 3
```

Have you any solution please? Thanks :-)

**Comment by bclozel** [comment]
@Andromed what happens when you do the following?
Which platform are you using (windows? linux?)

```
$ cd sagan-client
$ node -v
$ npm install
$ npm run build
```

**Comment by HFA-AlexByrd** [comment]
(Picking up for Andromed)

```cmd
 ~/dev/playground/sagan (master)
$ cd ./sagan-client

 ~/dev/playground/sagan/sagan-client (master)
$ node -v
v0.12.1

 ~/dev/playground/sagan/sagan-client (master)
$ npm install

> sagan@ prepublish %USERPROFILE%\dev\playground\sagan\sagan-client
> bower install --config.interactive=false


 ~/dev/playground/sagan/sagan-client (master)
$ npm run build

> sagan@ build %USERPROFILE%\dev\playground\sagan\sagan-client
> gulp build

[gulp] Using gulpfile %USERPROFILE%\dev\playground\sagan\sagan-client\gulpfile.js
[gulp] Starting 'minify-css'...
[gulp] Starting 'build-modules'...
[gulp] Starting 'copy-assets'...
[gulp] Starting 'bower-files'...
%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1249
                                        if (rejected) rejected(ex); else throw ex;
                                                                               ^
Error: Multiple anonymous defines encountered
    at %USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:963:19
    at loadScriptViaRequire (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js
:1575:4)
    at Object.priv.core.loadScript (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\
curl.js:1556:11)
    at Object.core.fetchResDef (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl
.js:951:9)
    at Object.core.fetchDep (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js
:1036:10)
    at getDep (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:906:21)
    at Object.core.getDeps (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:
888:6)
    at %USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1267:38
    at when (%USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:219:11)
    at %USERPROFILE%\dev\playground\sagan\sagan-client\node_modules\gulp-cram\node_modules\cram\amd_modules\curl\dist\curl-for-ssjs\curl.js:1267:5

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! sagan@ build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sagan@ build script 'gulp build'.
npm ERR! This is most likely a problem with the sagan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sagan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     %USERPROFILE%\dev\playground\sagan\sagan-client\npm-debug.log

**Comment by HFA-AlexByrd** [comment]
Looks like this might be the same issue as #506

**Comment by bclozel** [comment]
Yeah, Sagan does not build correctly right now on 0.12 - I'd like to completely revisit the client side build and get that fixed at the same time.
