### ISSUE TITLE
PUT to update releases does not seem to replace releases properly

### ISSUE THREAD

**Issue by olivergierke** [spring-io/sagan#733]
Replacing all releases of a project with a PUT request seems to fail in case the a currently existing release (i.e same groupId:artifactId:version) is submitted as well. I've seen exceptions in the production log hinting at duplicate ids. 

Currently, the only way to really replace release versions via the API seems to be deleting all of them first and then recreating them either by POSTing individual releases or PUTting them at once. Is there a special reason there's some merge logic going on for PUT requests? Shouldn't the release simply be replaced as is?

**Comment by dsyer** [comment]
I can reproduce this (I think) by running the site and using curl:

```
2017-08-08 11:49:15.139 ERROR 31897 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["PRIMARY_KEY_5 ON PUBLIC.PROJECT_RELEASELIST(PROJECT_ID, VERSIONNAME) VALUES ('spring-framework', '4.0.0.RELEASE', 116)"; SQL statement:
insert into Project_releaseList (Project_id, apiDocUrl, artifactId, groupId, isCurrent, refDocUrl, releaseStatus, repository_id, versionName) values (?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-193]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_5 ON PUBLIC.PROJECT_RELEASELIST(PROJECT_ID, VERSIONNAME) VALUES ('spring-framework', '4.0.0.RELEASE', 116)"; SQL statement:
insert into Project_releaseList (Project_id, apiDocUrl, artifactId, groupId, isCurrent, refDocUrl, releaseStatus, repository_id, versionName) values (?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	at org.hibernate.persister.collection.AbstractCollectionPersister.recreate(AbstractCollectionPersister.java:1311)
	at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:97)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:504)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy156.save(Unknown Source)
	at sagan.projects.support.ProjectMetadataService.save(ProjectMetadataService.java:38)
	at sagan.projects.support.ProjectMetadataController.updateProjectMetadata(ProjectMetadataController.java:79)
...
```

But, there is an integration test for the same scenario which doesn't fail, so I'm not sure how to proceed. If you can help me understand how the test can be passing, maybe we can make progress.

There's a bug in the test. So I changed it to do this:

```
    @Test
    public void projectMetadata_updateProject() throws Exception {
        Project project = service.getProject("spring-framework");
        List<Map<String, Object>> releases = new ArrayList<>();
        for (ProjectRelease release : project.getProjectReleases()) {
            release = release.createWithVersionPattern();
            Map<String, Object> map = getRelease(release);
            releases.add(map);
        }
        releases.iterator().next().put("version", "1.2.8.BUILD-SNAPSHOT");
        mockMvc
                .perform(
                        MockMvcRequestBuilders
                                .put("/project_metadata/spring-framework/releases").content(mapper.writeValueAsString(
                                        releases))
                                .contentType(MediaType.APPLICATION_JSON_UTF8))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith("application/json"))
                .andDo(docs("update_project"));
    }
```

See `sagan.projects.support.ProjectsMetadataApiTests.projectMetadata_updateProject()` for the test case.
