### ISSUE TITLE
fail to start up in idea

### ISSUE THREAD

**Issue by edwardthree** [spring-io/sagan#734]
fail to start up in idea 
the error info:

```:: Spring Boot ::        (v1.4.4.RELEASE)

2017-08-03 14:46:24.497  INFO 7528 --- [  restartedMain] sagan.SiteApplication                    : Starting SiteApplication on BuilderX640065 with PID 7528 (C:\Users\Administrator\IdeaProjects\sagan\sa
gan-site\build\classes\main started by Administrator in C:\Users\Administrator\IdeaProjects\sagan)
2017-08-03 14:46:24.506  INFO 7528 --- [  restartedMain] sagan.SiteApplication                    : The following profiles are active: standalone
2017-08-03 14:47:15.668  WARN 7528 --- [  restartedMain] sagan.support.github.GitHubConfig        : GitHub API access will be rate-limited at 60 req/hour
2017-08-03 14:47:28.897  INFO 7528 --- [  restartedMain] b.a.s.AuthenticationManagerConfiguration : 

Using default security password: 91f463fe-5b93-4657-8b47-edfa44bab9d8

2017-08-03 14:47:31.415  WARN 7528 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classPathFileSystemWatcher' defined in class path resource [org/springframework/boot/devtools/autoconfigure/LocalDevToolsAutoConfiguration$RestartConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.devtools.classpath.ClassPathFileSystemWatcher]: Factory method 'classPathFileSystemWatcher' threw exception; nested exception is java.lang.IllegalArgumentException: Folder 'C:\Users\Administrator\IdeaProjects\sagan\..\sagan-client\src' must exist and must be a directory
2017-08-03 14:47:31.464 ERROR 7528 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classPathFileSystemWatcher' defined in class path resource [org/springframework/boot/devtools/autoconfigure/LocalDevToolsAutoConfiguration$RestartConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.devtools.classpath.ClassPathFileSystemWatcher]: Factory method 'classPathFileSystemWatcher' threw exception; nested exception is java.lang.IllegalArgumentException: Folder 'C:\Users\Administrator\IdeaProjects\sagan\..\sagan-client\src' must exist and must be a directory
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at sagan.SiteApplication.main(SiteApplication.java:42) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.devtools.classpath.ClassPathFileSystemWatcher]: Factory method 'classPathFileSystemWatcher' threw exception; nested exception is java.lang.IllegalArgumentException: Folder 'C:\Users\Administrator\IdeaProjects\sagan\..\sagan-client\src' must exist and must be a directory
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 21 common frames omitted
Caused by: java.lang.IllegalArgumentException: Folder 'C:\Users\Administrator\IdeaProjects\sagan\..\sagan-client\src' must exist and must be a directory
	at org.springframework.util.Assert.isTrue(Assert.java:68) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.devtools.filewatch.FileSystemWatcher.addSourceFolder(FileSystemWatcher.java:124) ~[spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration.newFileSystemWatcher(LocalDevToolsAutoConfiguration.java:159) ~[spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration.access$000(LocalDevToolsAutoConfiguration.java:101) ~[spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration$1.getFileSystemWatcher(LocalDevToolsAutoConfiguration.java:142) ~[spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.devtools.classpath.ClassPathFileSystemWatcher.<init>(ClassPathFileSystemWatcher.java:61) ~[spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration.classPathFileSystemWatcher(LocalDevToolsAutoConfiguration.java:119) ~[spring-boot-devtools-1.4.4.RELEASE.jar:1.4.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 22 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:50554', transport: 'socket'

Process finished with exit code 1`

**Comment by dsyer** [comment]
Did you follow the instructions about how to run the site locally (https://github.com/spring-io/sagan/wiki/Run-the-site-locally)?

P.S. please format your logs and code snippets (use markdown, there's a quickstart button right underneath the text extry box).

**Comment by dsyer** [comment]
It might be that you just need to add a "/" to the end of the directory name in your IDE configuration. I am not an intellij user so the instructions mean nothing to me.

**Comment by dsyer** [comment]
I guess you configured IDEA wrong then. Did you try adding the "/"?

**Comment by edwardthree** [comment]
sorry I do not understand how to add the ‘/’.
please show me the way, thanks

**Comment by dsyer** [comment]
I'm not an intellij user. The instructions say "Make sure that this configuration refers to the sagan-site folder as a working directory." You have to interpret that as an intellij user.

**Comment by dsyer** [comment]
Actually, what version of the JVM are you using? This seems like a bug in that to me (failure to resolve a relative file to its absolute path).

**Comment by edwardthree** [comment]
the java version is  '1.8.0_131'

**Comment by dsyer** [comment]
Possibly IntelliJ is broken then. It works on the command line for you after all. I expect IntelliJ is monkeying around with the `java.io.FileSystem`. I would take it up with them, or maybe upgrade to the latest version and see if it works there.

If you run this program

```java
import java.io.File;
public class Main {
  public static void main(String[] args) throws Exception {
    System.err.println(new File("../foo").getAbsolutePath());
  }
}
```

Does it print a valid path? On the command line? In IntelliJ?

**Comment by edwardthree** [comment]
I print it like this
`'C:\Users\Administrator\Downloads\sagan-master\sagan-master\sagan-site\..\foo'`

**Comment by edwardthree** [comment]
the  above is in ecplise  like this
`'C:\Users\Administrator\Downloads\sagan-master\sagan-master\sagan-site\..\foo'`
the following is in idea
`C:\Users\Administrator\IdeaProjects\sagan\..\foo`

**Comment by dsyer** [comment]
In IDEA the working directory is different. You probably need to fix that,

**Comment by haoxiaopang** [comment]
just remove '../' before 'sagan-client/src/' in 'sagan-site/src/main/resources/application.yml'

**Comment by network2006** [comment]
“- ../sagan-client/src/”    改成  “- sagan-client/src/ ”   问题解决了。谢谢大佬！ @haoxiaopang
