### ISSUE TITLE
does not work with java 10

### ISSUE THREAD

**Issue by Jeansen** [spring-io/sagan#853]
Checked out the repo and ran `./gradlew :sagan-site:bootRun`.
This failed with the  error `Could not determine java version from '10.0.1'.`

I had to upgrade from gradle 4.1 to 4.5 or greater. More can be found here: https://github.com/gradle/gradle/issues/5764

Anyway, from then on, it does not matter which gradle version I use, I always get:

```
> Task :sagan-site:compileJava 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :sagan-site:bootRun FAILED
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:93)
        at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:56)
        at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:140)
        at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:546)
        at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartingEvent(RestartApplicationListener.java:67)
        at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
        at sagan.SiteApplication.main(SiteApplication.java:42)

```

Would be happy to see this work with versions other than Java 8 (which will be soon obsolete, anyway!)

**Comment by bclozel** [comment]
We've upgraded to Gradle 6.3 in the meantime.
We're in the process of upgrading all our dependencies so we should be soon JDK11 compatible.
Thanks!
