### ISSUE TITLE
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://github.com/login/oauth/access_token":

### ISSUE THREAD

**Issue by WeiXiaoxia** [spring-io/sagan#985]
I deployed Sagan web application to Aliyun server, but failed to login with GitHub third party. I use the built-in Tomcat, and the server can ping github.com website.
This is my log: 
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.5.18.RELEASE)

2020-07-08 19:20:48.496  INFO 4857 --- [           main] sagan.SiteApplication                    : Starting SiteApplication on iZbp1exgdlpkfrcg6eu9arZ with PID 4857 (/home/space/sagan-site-1.0.0.BUILD-SNAPSHOT.jar started by root in /home/space)
2020-07-08 19:20:48.504  INFO 4857 --- [           main] sagan.SiteApplication                    : The following profiles are active: standalone
2020-07-08 19:20:57.797  WARN 4857 --- [           main] sagan.support.github.GitHubConfig        : GitHub API access will be rate-limited at 60 req/hour
2020-07-08 19:20:59.177  INFO 4857 --- [           main] b.a.s.AuthenticationManagerConfiguration :

Using default security password: 60f9b679-26f5-40aa-8831-119e581273a2

2020-07-08 19:21:00.328  INFO 4857 --- [           main] sagan.SiteApplication                    : Started SiteApplication in 12.504 seconds (JVM running for 13.123)
2020-07-08 19:25:52.620 ERROR 4857 --- [p-nio-80-exec-3] o.s.s.c.web.ProviderSignInController     : Exception while completing OAuth 2 connection:

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://github.com/login/oauth/access_token": Connect to github.com:443 [github.com/47.31.167.15] failed: 连接超时; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to github.com:443 [github.com/47.31.167.15] failed: 连接超时
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:674) ~[spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:621) ~[spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:388) ~[spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.social.oauth2.OAuth2Template.postForAccessGrant(OAuth2Template.java:242) ~[spring-social-core-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
        at org.springframework.social.oauth2.OAuth2Template.exchangeForAccess(OAuth2Template.java:144) ~[spring-social-core-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
        at org.springframework.social.connect.web.ConnectSupport.completeConnection(ConnectSupport.java:160) ~[spring-social-web-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
        at org.springframework.social.connect.web.ProviderSignInController.oauth2Callback(ProviderSignInController.java:228) ~[spring-social-web-1.1.6.RELEASE.jar!/:1.1.6.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [urlrewritefilter-4.0.4.jar!/:4.0.4]
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [urlrewritefilter-4.0.4.jar!/:4.0.4]
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [urlrewritefilter-4.0.4.jar!/:4.0.4]
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) [urlrewritefilter-4.0.4.jar!/:4.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
```

**Comment by bclozel** [comment]
Is GitHub being blacklisted from where you are, or do you need a specific proxy to access github?

See this line in the error logs:
`nested exception is org.apache.http.conn.HttpHostConnectException: Connect to github.com:443 [github.com/47.31.167.15]`

Note that `47.31.167.15` doesn't seem to belong to GitHub.

**Comment by WeiXiaoxia** [comment]
> Is GitHub being blacklisted from where you are, or do you need a specific proxy to access github?
> 
> See this line in the error logs:
> `nested exception is org.apache.http.conn.HttpHostConnectException: Connect to github.com:443 [github.com/47.31.167.15]`
> 
> Note that `47.31.167.15` doesn't seem to belong to GitHub.

Thank for your answer. I took a detour. I found the IP address of GitHub again and modified the hosts file of the server.

**Comment by WeiXiaoxia** [comment]
> Is GitHub being blacklisted from where you are, or do you need a specific proxy to access github?
> 
> See this line in the error logs:
> `nested exception is org.apache.http.conn.HttpHostConnectException: Connect to github.com:443 [github.com/47.31.167.15]`
> 
> Note that `47.31.167.15` doesn't seem to belong to GitHub.

Thank for your answer. I took a detour. I found the IP address of GitHub again and modified the hosts file of the server.

**Comment by bclozel** [comment]
So your DNS was lying to your application? If that's the case, there's nothing we can do here to improve the situation unfortunately.
